---
title: "Homework 5"
author: "Kayna Hobbs-Murphy"
date: "11/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(tidyverse)
library(lubridate)
library(scales)
library(dplyr)
library(data.table)
library(zoo)
```


```{r}
homicides <- read_csv(file = "data/homicide-data.txt")
```
```{r}
head(homicides)
data.class(homicides$reported_date)
```

```{r}
homicides <- homicides %>% 
  unite(col= city_name, city, state, sep=", ") 

balt_homicides <- homicides %>% 
  filter(city_name == "Baltimore, MD")

balt_homicides <- balt_homicides %>% 
  mutate(reported_date = ymd(reported_date))

head(balt_homicides)
```
```{r}
seasons = function(x){
  if(x %in% c(11,12,1,2,3,4)) return("Winter")
  if(x %in% 5:10) return("Summer")
}

balt_homicides$season = sapply(month(balt_homicides$reported_date), seasons)

head(balt_homicides)
```


```{r}
monthly = function(x){
  if(x %in% c(1)) return(FUN=sum(x %in% c(1)))
  if(x %in% c(2)) return(FUN=sum(x %in% c(2)))
  if(x %in% c(3)) return(FUN=sum(x %in% c(3)))
  if(x %in% c(4)) return(FUN=sum(x %in% c(4)))
  if(x %in% c(5)) return(FUN=sum(x %in% c(5)))
  if(x %in% c(6)) return(FUN=sum(x %in% c(6)))
  if(x %in% c(7)) return(FUN=sum(x %in% c(7)))
  if(x %in% c(8)) return(FUN=sum(x %in% c(8)))
  if(x %in% c(9)) return(FUN=sum(x %in% c(9)))
  if(x %in% c(10)) return(FUN=sum(x %in% c(10)))
  if(x %in% c(11)) return(FUN=sum(x %in% c(11)))
  if(x %in% c(12)) return(FUN=sum(x %in% c(12)))
}

balt_homicides$monthly = sapply(month(balt_homicides$reported_date), monthly)

head(balt_homicides)
```



```{r, fig.width=12, fig.height=3}
balt_homicides %>% 
  ggplot()+ 
  geom_histogram(aes(fill = season, x = reported_date), color = "black", binwidth = 27)+
  scale_fill_manual(values = c("grey", "skyblue"))+
  geom_vline(aes(xintercept = as.numeric(ymd("2015-04-12"))),
             color = "red",
             linetype = "dashed",
             size = 2,
             show.legend = NA)+ 
  geom_text(label= "Arrest of
            Freddie Gray",
            x=as.numeric(ymd("2015-04-12")),
            y=40,
            color = "white",
            hjust = 1,
            vjust = 0.75)+
  geom_smooth(aes(x=reported_date, y=monthly), color = "blue", adjust = 1/4, size = 1.5)+
  theme_dark()+
  theme(legend.position = "bottom")+
  scale_y_continuous(name = "Monthly homocides", breaks = c(0, 10, 20, 30, 40))+
  labs(title="Homicides in Baltimore, MD",
       x="Date",
       fill = "")
```

